version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME:-rag}
      POSTGRES_USER: ${DB_USER:-rag}
      POSTGRES_PASSWORD: ${DB_PASS:-rag}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    build: .
    environment:
      APP_PORT: 8080
      DB_URL: jdbc:postgresql://db:5432/${DB_NAME:-rag}
      DB_USER: ${DB_USER:-rag}
      DB_PASS: ${DB_PASS:-rag}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-*}
      SECURITY_ALLOWLIST: ${SECURITY_ALLOWLIST:-/actuator/health,/v3/api-docs,/swagger-ui,/swagger-ui.html}
      RATE_LIMIT_CAPACITY: ${RATE_LIMIT_CAPACITY:-300}
      RATE_LIMIT_PERIOD_MINUTES: ${RATE_LIMIT_PERIOD_MINUTES:-5}
      SWAGGER_DOCS_ENABLED: ${SWAGGER_DOCS_ENABLED:-true}
      SWAGGER_REQUEST_SERVER_URL: ${SWAGGER_REQUEST_SERVER_URL:-http://localhost:8080}
      API_KEYS: ${API_KEYS:-rag-chat-token}
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  dbdata:
