server:
  port: ${APP_PORT:8081}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/rag}
    username: ${DB_USER:rag}
    password: ${DB_PASS:rag}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true

security:
  api:
    keys: ${API_KEYS:rag-chat-token}


cors:
  allowedOrigins: ${CORS_ALLOWED_ORIGINS:*}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

ratelimit:
  capacity: ${RATE_LIMIT_CAPACITY:300}
  periodMinutes: ${RATE_LIMIT_PERIOD_MINUTES:5}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    persistAuthorization: true
